name: Chrome

on: push

jobs:
  chrome:
    runs-on: ubuntu-18.04
    steps:
      - name: Print network configuration
        run: ifconfig
      - name: Checkout
        uses: actions/checkout@v3
      - name: Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm run start
          browser: chrome
